import Provider from '@/context/Provider'
import './globals.css'
import { Inter } from 'next/font/google'
import QueryProvider from '@/context/QueryProvider'
import { UserContextProvider } from '@/context/UserContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <QueryProvider>
      <Provider>
        <UserContextProvider>
          
      <body className={inter.className}>
        {children}
        </body>
        </UserContextProvider>
      </Provider>
      </QueryProvider>
    </html>
  )
}
